# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
description: > # this means to ignore newlines until "baseurl:"
  We're getting married on 29th September 2016!

baseurl: "" # the subpath of your site, e.g. /blog

url: "https://jolowedshannah.com/" # the base hostname & protocol for your site


#images
imagesBannerRSVP: "https://drive.google.com/uc?export=view&id=1fOAsl0fGYKKw2TPODR2KQHwjvpl0Z2jG"
imagesBannerDressCode: "https://drive.google.com/uc?export=view&id=1byzcjPDQL2A8gpwcVpXIcy1vX7TO21rG"
imagesBannerAccomodation: "https://drive.google.com/uc?export=view&id=1Uak93hLGUufEm3e6JgISJorbsQuVCSdR"
imagesBannerLocation: "https://drive.google.com/uc?export=view&id=1uPMSc2HEGX7KzR8f0UhJs18XG2fRZmKn"
imagesBannerSchedule: "https://drive.google.com/uc?export=view&id=14qsVTK2bKw_fvMxzdwOb2yzjB5Wj_Iyd"
imagesBannerMeta: "https://drive.google.com/uc?export=view&id=1J0xUzdjxMoWSCgT2opk3lXmgbNz9AFHv"

imagesAccomodationPintoresco: "https://drive.google.com/uc?export=view&id=16j9MQvFaKTTtojrlZqJJGg32c3ajG3Fb"
imagesAccomodationHaciendaIsabela: "https://drive.google.com/uc?export=view&id=1S2FZ1LBEczBNpvIE6DTfh_oXKjAY4kCc"
imagesAccomodationHardinDeAsis: "https://drive.google.com/uc?export=view&id=1UjQWJrj9GsGu0srW9i6dIrklfVnZeRRu"
imagesAccomodationLaBellaBotiqueHotel: "https://drive.google.com/uc?export=view&id=10YbEjA1Npk92RgiPoBUXKyBj3otrCYgF"

#icons
iconsScheduleCeremony: "https://drive.google.com/uc?export=view&id=1znsX1U_3Yq7ZkULk1PvDcdl5M_9CROkV"
iconsScheduleDrinks: "https://drive.google.com/uc?export=view&id=1P9mHMswDdsKtr0fqKMYNWNetkkKtp_8U"
iconsScheduleDinner: "https://drive.google.com/uc?export=view&id=11P0XerddKl3vQSSm6cKqT9Go521DtsJh"
iconsScheduleSpeeches: "https://drive.google.com/uc?export=view&id=1inEQGzG0nztxRiJB0DNEIvgeKlM1a226"
iconsScheduleMusic: "https://drive.google.com/uc?export=view&id=10AG1cyKPK_QGBTt3h8HFTeQBGHcVEXe0"
iconsScheduleSupper: "https://drive.google.com/uc?export=view&id=1KwV2cIoBThvzEcxdse-J0IGNFAenE_Nu"
iconsScheduleSleep: "https://drive.google.com/uc?export=view&id=1xTdtejDGx2ph-SGvhknq0N6LYHqDyDFX"
iconsFavIcon: "https://drive.google.com/uc?export=view&id=1KgnJVPFucFmLYo_rMjheEQHaaKaGpHvO"

# Build settings
markdown: kramdown

# only build incrementally
incremental: true

# exclude node_modules from jekyll generation
exclude: [node_modules, Gulpfile.js, package.json, package-lock.json, README.md, logo.sketch, Gemfile, Gemfile.lock]

# do not delete these folders when regenerating jekyll site
keep_files: [css, js, images]

# compress html
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
  blanklines: false